name: CMake Fedora

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - container: fedora:35
            compiler: gcc  # GCC 11
            ignore-errors: false
          # TODO(cblichmann): Add clang-13 build to matrix (currently fails)
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.ignore-errors }}

    container:
      image: ${{ matrix.container }}

    steps:
    - uses: actions/checkout@v2

    - name: Install build tools
      run: |
        dnf update -y
        dnf install -y git make automake patch glibc-static libstdc++-static \
          cmake ninja-build python3 python3-pip clang-devel libcap-devel

    - name: Install/configure Clang compiler toolchain
      if: matrix.compiler == 'clang'
      run: |
        echo "CXX=clang++" >> $GITHUB_ENV
        echo "CC=clang" >> $GITHUB_ENV

    - name: Create Build Environment
      run: |
        pip3 install absl-py clang
        cmake -E make_directory $GITHUB_WORKSPACE/build

    - name: Configure CMake
      run: cmake $GITHUB_WORKSPACE -G Ninja -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      run: cmake --build $GITHUB_WORKSPACE --config $BUILD_TYPE
